on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  install_kbsdk_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: pull sdk image and test
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        GITHUB_ACTIONS_CI: 1
      run: |
        docker pull kbase/kb-sdk:develop
        echo "installing kb-sdk script to $GITHUB_WORKSPACE"
        docker tag kbase/kb-sdk:develop kbase/kb-sdk:latest
        docker run kbase/kb-sdk genscript > $GITHUB_WORKSPACE/kb-sdk
        echo "done, giving run permissions to script"
        chmod 755 $GITHUB_WORKSPACE/kb-sdk
        echo "done, running tests"
        $GITHUB_WORKSPACE/kb-sdk test
